swagger: '2.0'
info:
  title: ozonmp/act_device_api/v1/act_device_api.proto
  version: version not set
tags:
  - name: Insulter
produces:
  - text/plain
paths:
  /name/{yourName}:
    get:
      summary: Рандомное обзывательство
      operationId: Insulting
      responses:
        '200':
          description: A successful response.
        default:
          description: An unexpected error response.
      parameters:
        - name: yourName
          in: path
          required: true
    /age/{yourAge}::
    get:
      summary: Получить дату сметри
      operationId: DeathClock
      responses:
        '200':
          description: A successful response.
           default:
          description: An unexpected error response.
         - name: yourAge
          in: path
          required: true
